### ISSUE TITLE
Code snippets seems not working

### ISSUE THREAD

**Issue by redfish-lee** [googlesamples/md2googleslides#11] opened 2017-08-24 07:02 UTC

**Comment by tomer-ben-david** [comment] 2017-08-31 19:16
try removing the prefix spaces in each line

**Comment by rjhilgefort** [comment] 2018-01-03 20:28
Work for me.

**Comment by sqrrrl** [comment] 2018-01-04 18:02
Since no steps to reproduce, closing. Re-open if still an issue and provide an example.

**Closed by sqrrrl** 2018-01-04 18:02 UTC
